<?php
/**
 * Created by PhpStorm.
 * User: uu103087
 * Date: 2018/02/13
 * Time: 20:37
 */

namespace app\tests\unit;
use PHPUnit\Framework\TestCase;

class LogicTest extends TestCase
{

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_check_if_tests_can_run()
    {
        $this->assertEquals(1, true, "Tests are running and assertions are working");
    }

    public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}